name: uft
base: core22
version: '0.0.1'
summary: universal flash tool
description: |
  It's a collection of many flash tool.

grade: stable
confinement: classic

apps:
  uft:
    command: bin/uft
    environment:
      PATH: '$SNAP/usr/sbin/:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH'
      PYTHONPATH: '$SNAP/lib/python3.10/site-packages:$PYTHONPATH'

parts:
  uft:
    plugin: python
    source: uft
    build-packages:
      - python3-pip
    stage-packages:
      - uuu
    stage-snaps:
      - on arm64:
        - imx6-img-flash-tool/latest/edge

    override-build: |
      python3 -m venv /home/ubuntu/uft/parts/uft/install
      pip3 install .

    organize:
      imx_usb: usr/local/bin/
      utp_com: usr/local/bin/
      flash.sh: usr/loca/bin/


    override-stage: |
      if [ -f $CRAFT_PART_INSTALL/usr/local/bin/flash.sh ]; then
        echo "Fixing `imx6-img-flash-tool` binaries path"
        sed -i 's/imx6-img-flash-tool\.imx-usb/imx_usb/g' $CRAFT_PART_INSTALL/usr/local/bin/flash.sh
        sed -i 's/imx6-img-flash-tool\.utp-com/utp_com/g' $CRAFT_PART_INSTALL/usr/local/bin/flash.sh
        mv $CRAFT_PART_INSTALL/usr/local/bin/flash.sh $CRAFT_PART_INSTALL/usr/local/bin/imx6_flash
      fi
      craftctl default
