name: uft
base: core24
version: '0.0.1'
summary: universal flash tool
description: |
  It's a collection of many flash tool.

grade: stable
confinement: classic

apps:
  uft:
    command: bin/uft
    environment:
      PATH: '$SNAP/usr/sbin/:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH'
      PYTHONPATH: '$SNAP/lib/python3.12/site-packages:$PYTHONPATH'

parts:
  uft:
    plugin: python
    source: uft
    build-packages:
      - python3
      - python3-venv       # needed to create the venv
      - python3-dev        # if you build native wheels
      - gcc 
    stage-packages:
      - python3.12-minimal
      - python3-tk
      - libpython3.12-stdlib
      - uuu

  libusb:
    plugin: autotools
    source: https://github.com/libusb/libusb.git
    source-type: git
    source-tag: v1.0.28
    build-packages:
      - libtool
      - pkg-config
      - autoconf
      - automake
      - libudev-dev
    autotools-configure-parameters:
      - --prefix=/usr
    organize:
      usr/include/libusb-1.0/libusb.h: usr/include/

  libxml2:
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/libxml2.git
    source-type: git
    source-tag: v2.12.5
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - libtool
      - pkg-config
      - zlib1g-dev
      - python3-minimal  # libxml2's build system sometimes wants Python
    organize:
      usr/include/libxml2/libxml: usr/include/libxml

  qdl:
    plugin: make
    source: https://github.com/andersson/qdl.git
    source-tag: v2.1
    after: [libusb, libxml2]
    build-environment:
      - CPPFLAGS: "-I$SNAPCRAFT_STAGE/usr/include"
      - LDFLAGS: "-L$SNAPCRAFT_STAGE/usr/lib"
    build-packages:
      - build-essential
    override-build: |
      make
      install -D qdl $SNAPCRAFT_PART_INSTALL/usr/bin/qdl

